version: '3.9'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloudbm
      MYSQL_USER: cloudbm
      MYSQL_PASSWORD: cloudbm
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql-config:/etc/mysql/conf.d
volumes:
  db_data: